version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: temp_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: temperatures

  backend:
    build: ./backend
    container_name: temp_backend
    restart: always
    ports:
      - "443:443"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/temperatures
      - PORT=443
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: temp_frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data: